version: '3'
services:
  octopus1:
    image: octopusdeploy/octopusdeploy:${OCTOPUS_SERVER_TAG}
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 4G
    privileged: ${PRIVILEGED}
    environment:
      ACCEPT_EULA: ${ACCEPT_OCTOPUS_EULA}
      OCTOPUS_SERVER_NODE_NAME: octopus1
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      MASTER_KEY: ${MASTER_KEY}
      DISABLE_DIND: ${DISABLE_DIND}
    ports:
      - 8080:8080
      - 10943:10943
    volumes:
      - octopus-import:/import
      - octopus-repository:/repository
      - octopus-artifacts:/artifacts
      - octopus-tasklogs:/taskLogs
      - octopus-cache:/cache
  octopus2:
    image: mipdevregistryops.azurecr.io/mipoctopusnode:node2
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 4G
    privileged: ${PRIVILEGED}
    environment:
      ACCEPT_EULA: ${ACCEPT_OCTOPUS_EULA}
      OCTOPUS_SERVER_NODE_NAME: octopus2
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      MASTER_KEY: ${MASTER_KEY}
      DISABLE_DIND: ${DISABLE_DIND}
    ports:
      - 8081:8081
      - 10944:10944
    depends_on:
      - octopus1
    volumes:
      - octopus-import:/import
      - octopus-repository:/repository
      - octopus-artifacts:/artifacts
      - octopus-tasklogs:/taskLogs
      - octopus-cache:/cache
volumes:
  octopus-import:
    driver: azure_file
    driver_opts:
      share_name: octopus-import
      storage_account_name: devopsmipsa
  octopus-repository:
    driver: azure_file
    driver_opts:
      share_name: octopus-repository
      storage_account_name: devopsmipsa
  octopus-artifacts:
    driver: azure_file
    driver_opts:
      share_name: octopus-artifacts
      storage_account_name: devopsmipsa
  octopus-tasklogs:
    driver: azure_file
    driver_opts:
      share_name: octopus-tasklogs
      storage_account_name: devopsmipsa
  octopus-cache:
    driver: azure_file
    driver_opts:
      share_name: octopus-cache
      storage_account_name: devopsmipsa
      